# Generated by Django 3.2.7 on 2021-09-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210917_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
